### ISSUE TITLE
[bconds] Submitting packages using %autochangelog fails

### ISSUE THREAD

**Issue by hrnciar** [hroncok/whatdoibuild#6]
~~~~
 • Cloning dask into "_fedpkg_cache_dir/dask::bootstrap:::"...    • Patching dask.spec
Traceback (most recent call last):
  File "/home/thrnciar/python-maint/whatdoibuild/bconds.py", line 298, in <module>
    something_was_submitted |= scratchbuild_patched_if_needed(component_name, bcond_config)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thrnciar/python-maint/whatdoibuild/bconds.py", line 216, in scratchbuild_patched_if_needed
    run('rpmdev-bumpspec', '--rightmost', specpath)
  File "/home/thrnciar/python-maint/whatdoibuild/bconds.py", line 45, in run
    return subprocess.run(cmd, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('rpmdev-bumpspec', '--rightmost', PosixPath('_fedpkg_cache_dir/dask::bootstrap:::/dask.spec'))' returned non-zero exit status 2.
~~~~

https://github.com/hroncok/whatdoibuild/blob/0a9f08fbd2648be6a71e22342f8326a680070141/bconds.py#L210

**Comment by hroncok** [comment]
A package dask does not exist, it's python-dask. And the cloning should have failed, but @hrnciar had a custom change in the code that prevented the failure.
